version: "3.7"

services:
  server:
    container_name: chat-server
    build:
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../:/app

  client:
    container_name: chat-client
    build:
      dockerfile: client/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ../:/app
